AudioStream/AudioStream/Controllers/UploadPageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using AudioStream.Data;
using AudioStream.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using AudioStream.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Server;


namespace AudioStream.Controllers
{
    public class UploadPageController : Controller
    {
        //                /                      /          2 variables and a constructor used to set reference to SQLDB and fileserver
        private readonly AudioStreamContext  _context;
        private readonly AudioStream2Context _DbContext;
        private IHostingEnvironment _env;
        public UploadPageController(IHostingEnvironment env, AudioStreamContext context, AudioStream2Context contez)
        {
            _env       = env    ;
            _context   = context;
            _DbContext = contez;
        }
        //            /                   /                    /                /                        /                            /
        public IActionResult Index()
        {
            var userid = User.Identity.Name;
            var user = _context.User.FirstOrDefault(p => p.Email == userid);


            return View(user);
        }
        //User edits bio
        public async Task<IActionResult> BioEdit(string bio)
        {
            var userid = User.Identity.Name;
            var user = _context.User.FirstOrDefault(p => p.Email == userid);
            //user       = user.Where(s => s.Email == userid);
            user.bio = bio;
             _context.SaveChanges();

            return RedirectToAction("Index");


        }

        //User chooses file and fills out details 
        public async Task<IActionResult> FileUpload(IFormFile file, string songName, string Genre)
        {
            //create file path / store file path
            string fileName = songName + ".mp3"          ;     
            var    dir      = _env.WebRootPath           ;
            var    fullpath = Path.Combine(dir, fileName);

            //Add uplaoded file to file base     / saves files to server with precreated filepath name 
            using (var fileStream = new FileStream(Path.Combine(dir, fileName), FileMode.Create, FileAccess.Write))
            {   file.CopyTo(fileStream);    }

            //Retreive user details from identity/ current user id / authenticated session /    /    /     /    /    
            var    userid        = User.Identity.Name   ;    // retreieve session ID
            var    date          = DateTime.Now         ;    // retreive  date
            string artistNameStr = ""                   ;    // create empty string field
            var    uses          = _context.User        ;    // begin user iteration
            foreach (User d in uses)
            {
                if(d.Email == userid)
                {
                    artistNameStr = d.Name;                  // set artist name to string field 
                }
            }
            //            /             /              /               /             /           /          /      /

            //This creates an instance of our song model, stores it as a variable, and saves it into the database  /           /          / 
            //       /             /           pass previously generated values to song constructor           /           /          /           /
            var   song   = new Song {ArtistName=artistNameStr, Artist = userid, Genre = Genre, PathVal = fullpath, ReleaseDate = date, Title = songName };
                  _context.Add(song);              
            await _context.SaveChangesAsync();
            
            ////////////////////////////////////////////////////////////////
            ///TODO : add a "successfully uploaded song" blurb ////////////
            ///////////////////////////////////////////////////////////////  
            ///return to index page          
            return RedirectToAction("Index");
            ////////////////////////////////////////////////////////////////
        }
    }
}

AudioStream/AudioStream/Views/UploadPage/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using AudioStream.Areas.Identity.Data

@inject SignInManager<AudioStreamUser> SignInManager
@inject UserManager<AudioStreamUser> UserManager
@model User
@{
    ViewData["Title"] = "Upload";
}

<h1>Upload</h1>

<p>this is the upload page</p>

@if (SignInManager.IsSignedIn(User))
{
    if (Model.ArtistAccount==true)
    {
    <div>
        <h3>Single File Upload</h3>
        <form asp-controller="UploadPage" asp-action="FileUpload"
              enctype="multipart/form-data" actionmethod="post">
            <input type="file" name="file" />
            <br />
            <p> <input type="text" name="songName" /> Song Title </p>
            @*<p> <input type="" name="Genre" /> Genre</p>*@
        <select name="Genre">
            <option value="phonk">phonk</option>
            <option value="vapor">vapor</option>
            <option value="drill">drill</option>
            <option value="new wave">new wave</option>
            <option value="trap">trap</option>
            <option value="crunk">crunk</option>
            <option value="old school">old school</option>
            <option value="distorted 808s">distorted 808s</option>
            

            <option value="witch house">witch house</option>
            <option value="shoegaze">shoegaze</option>
            <option value="ambient">ambient</option>
            <option value="vaporwave">vaporwave</option>
            <option value="seapunk">seapunk</option>
            <option value="indie">indie</option>
            <option value="dream pop">dream pop</option>

            <option value="psychedelic rock">psychedelic rock</option>
            <option value="alternative rock">alternative rock</option>
            <option value="math rock">math rock</option>
            <option value="hardcore">hardcore</option>
            <option value="post hardcore">post hardcore</option>
            <option value="metal">metal</option>
            <option value="death metal">death metal</option>
            <option value="house music">house music</option>
            <option value="soul">soul</option>
            <option value="jazz">jazz</option>
            <option value="electronic jazz">electronic jazz</option>
            <option value="r&b">r&b</option>
            <option value="reggae">reggae</option>
            <option value="lo-fi">lo-fi</option>
            <option value="classic dance">classic dance</option>
            <option value="deep house">deep house</option>
            <option value="progressive house">progressive house</option>
            <option value="trance">trance</option>
            <option value="dubstep2008">dubstep (2008)</option>
            <option value="hardstyle">hardstyle</option>
            <option value="riddim">riddim</option>
            <option value="drum n bass">drum n bass</option>
            <option value="jungle">jungle</option>

        </select>
            <label>Genre</label>
            <br />
            <button type="submit">Submit</button>
        </form>
    </div>


    <h1>Edit Bio</h1>
    <form asp-controller="UploadPage" asp-action="BioEdit"
          enctype="multipart/form-data" actionmethod="post">
        edit Bio: 
        <input type ="text" name="bio" />
        <button type="submit">Save Bio Changes</button>

    </form>
    }
    else
    {
        <p>You must have a verified artist account to post music and have a bio.</p>
    }
}
else
{
    <p>You must be signed in to upload music</p>
}

@*@UserManager.GetUserName(User)*@