AudioStream/AudioStream/Models/Song.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AudioStream.Models
{
    public class Song
    {
        //metadata for songs 
        public int      Id             { get; set; }
        public string   Title          { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime ReleaseDate    { get; set; }
        public string   Genre          { get; set; }

        //user email gets stored here
        public string   Artist         { get; set; }

        public string   PathVal        { get; set; }

        //This is the name that gets displayed
        public string  ArtistName      { get; set; }

        public int     Likes           { get; set; }
        public int     Dislikes        { get; set; }

    }
}

//Make sure to use EntityFrameworkCore\[command] ie 
//                  EntityFrameworkCore\Update-Database
//                  EntityFrameworkCore\Add-Migration migrationName -Context alteredContext
//                      when editing database as both entityframework and entityframeworkcore are installed 

AudioStream/AudioStream/Controllers/SongsController.cs
using AudioStream.Data;
using AudioStream.Migrations;
using AudioStream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using System.Collections;


namespace AudioStream.Controllers
{
    public class SongsController : Controller
    {
        private readonly AudioStreamContext _context;

        public SongsController(AudioStreamContext context)
        {
            _context = context;
        }

        // GET: Songs
        //match artists to songs and return a list
        public async Task<IActionResult> Index(string genre, string artistSelection)
        {
            //order songs by date and return 100 newest songs in dB
            var songs = from m in _context.Song
                        select m;
            songs = songs.OrderByDescending(s=>s.ReleaseDate).Take(100);

            //filter by genre
            if(genre != null)
            {
                if (genre != "all")
                {
                    songs = songs.Where(s => s.Genre == genre);
                }
            }

            //filter by artist
            if (artistSelection != null)
            {
                songs = songs.Where(s => s.ArtistName == artistSelection);
                ViewData["ArtistSelection"] = " by " + artistSelection;
            }
            else ViewData["ArtistSelection"] = "";

            ViewData["GenreSelection"]  = genre;
            

            //return songs list to page 
            return View(await songs.ToListAsync());
        }
         
        //Adds a songs to a users list of liked songs, removes songs from dislike list, changes the songs count of likes/dislikes
        public void LikeSong(Song song)
        {
            //WHat will happen is that a songID string will be sent to this fucntion
            //the user model will have a string value with all its liked songs
            //separated by .,.    
            //we will split this string into an array of strings, and then
            //compare to the songid thta has been sent, and use this evaulation to decide if we 
            //add a like to the song and add the somg to the liked list

            //initiate needed variables
            var userid = User.Identity.Name;
            bool check = false;
            var ss3 = song.Id.ToString();

            //grab the user object for the logged in identity
            var user = _context.User.FirstOrDefault(p => p.Email == userid);

            //grabs a reference to the song in the database for editing
            var songToEdit = _context.Song.FirstOrDefault(p => p.Id == song.Id);

            //iterate through songs that the user likes
           // 
           //     var x = user.LikedSongs.Length - 1;
          //      for (int i = 0; i < x; i++)
          //      {
          //          if (user.LikedSongs[i] == ss3)
          //              check = true;
           //         }
          //      }
            
            //if user has not liked the afforementioned song, add the song to the user's list of liked songs 
            //we add one like to the songs like count
            if(check==false)
            {
         //       user.LikedSongs.Append(ss3);
          //      songToEdit.Likes += 1;
            }

            //here we see if the song has previously been in the user's list of disliked songs
            bool check2 = false;
            var numToR = 0;
         //   x = user.DislikedSongs.Length - 1;
          //  for(int i = 0; i < x; i ++)
          //  {
         //       if(user.DislikedSongs[i] == ss3)
         //       {
         //           check2 = true;
          //          numToR = i;
          //      }
          //  }

            //if the song had been previously found in the user's list of disliked songs, we remove it here
            //we also remove "1" from the count of dislikes the song currently holds
            if (check2==true)
         //   {
          //      string[] newArray = new string[0];
          //      for(int i = 0; i < x; i ++)
         //       {
         //           if(i!=numToR)
         //           {
         //               newArray.Append(user.DislikedSongs[i]);
        //            }
         //       }
          //      user.DislikedSongs = newArray;
         //       songToEdit.Dislikes -= 1;
         //       
         //   }


            _context.SaveChanges();

        }

        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Song
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // GET: Songs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Genre,Artist")] Song song)
        {
            if (ModelState.IsValid)
            {
                _context.Add(song);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(song);
        }

        // GET: Songs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Song.FindAsync(id);
            if (song == null)
            {
                return NotFound();
            }
            return View(song);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Genre,Artist")] Song song)
        {
            if (id != song.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(song);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SongExists(song.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(song);
        }

        // GET: Songs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var song = await _context.Song
                .FirstOrDefaultAsync(m => m.Id == id);
            if (song == null)
            {
                return NotFound();
            }

            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var song = await _context.Song.FindAsync(id);
            _context.Song.Remove(song);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SongExists(int id)
        {
            return _context.Song.Any(e => e.Id == id);
        }
    }
}

AudioStream/AudioStream/Views/Songs/Create.cshtml
@model AudioStream.Models.Song

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Song</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AudioStream/AudioStream/Views/Songs/Delete.cshtml
@model AudioStream.Models.Song

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Song</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AudioStream/AudioStream/Views/Songs/Details.cshtml
@model AudioStream.Models.Song

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Song</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Artist)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AudioStream/AudioStream/Views/Songs/Edit.cshtml
@model AudioStream.Models.Song

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Song</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

AudioStream/AudioStream/Views/Songs/Index.cshtml
@model IEnumerable<AudioStream.Models.Song>

@{
    ViewData["Title"] = "Index";
}

<h1>Stream</h1>

@*<p>
    <a asp-action="Create">Create New</a>
</p>
    *@
<p>New Music - @ViewData["GenreSelection"] @ViewData["ArtistSelection"]</p>


<form asp-controller="Songs" asp-action="Index">
    <p>
        Genre Selection: 
        <select name="genre">
            <option value="all">all</option>
            
            <option value="phonk">phonk</option>
            <option value="vapor">vapor</option>
            <option value="drill">drill</option>
            <option value="new wave">new wave</option>
            <option value="trap">trap</option>
            <option value="crunk">crunk</option>
            <option value="old school">old school</option>
            <option value="distorted 808s">distorted 808s</option>
           

            <option value="witch house">witch house</option>
            <option value="shoegaze">shoegaze</option>
            <option value="ambient">ambient</option>
            <option value="vaporwave">vaporwave</option>
            <option value="seapunk">seapunk</option>
            <option value="indie">indie</option>
            <option value="dream pop">dream pop</option>

            <option value="psychedelic rock">psychedelic rock</option>
            <option value="alternative rock">alternative rock</option>
            <option value="math rock">math rock</option>
            <option value="hardcore">hardcore</option>
            <option value="post hardcore">post hardcore</option>
            <option value="metal">metal</option>
            <option value="death metal">death metal</option>
            <option value="house music">house music</option>
            <option value="soul">soul</option>
            <option value="jazz">jazz</option>
            <option value="electronic jazz">electronic jazz</option>
            <option value="r&b">r&b</option>
            <option value="reggae">reggae</option>
            <option value="lo-fi">lo-fi</option>
            <option value="classic dance">classic dance</option>
            <option value="deep house">deep house</option>
            <option value="progressive house">progressive house</option>
            <option value="trance">trance</option>
            <option value="dubstep2008">dubstep (2008)</option>
            <option value="hardstyle">hardstyle</option>
            <option value="riddim">riddim</option>
            <option value="drum n bass">drum n bass</option>
            <option value="jungle">jungle</option>
        </select>
        Artist Search:
        <input type="text" name="artistSelection" class="small"/>
        <input type="submit" value="filter songs" />
    </p>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                <h4>Music</h4>
            </th>
            

            <th>
                <h4>Title</h4>
            </th>
            <th></th>
            <th>
                <h4>Likes</h4>
            </th>
            <th></th>
            <th>
                @*@Html.DisplayNameFor(model => model.ArtistName) *@
                <h4>Artist</h4>
            </th>
            <th>
                <h4>Genre</h4>
            </th>
            <th>
                <h4>Release Date</h4>
            </th>

            <th></th>
        </tr>
    </thead>
      
    <tbody>
        @foreach (var item in Model)
        {
            
            <tr>
                <td>
                    <audio controls preload="auto" onended="endSong(id)" onplay="playSong(id)" class="songs" id="@item.Id">
                        <source src="@Url.Content("~/"+item.Title+".mp3")" type="audio/mpeg">
                    </audio>
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.Likes)
                    <form asp-controller="Songs" asp-action="LikeSong">
                        
                        <input type="submit" value="Like" item="song" />
                    </form>
                </td>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.ArtistName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ReleaseDate)
                </td>

                @*
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                *@
            </tr>
        }
    </tbody>
</table>

<script src="~/js/site.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
@*
<script type="text/javascript">
    $(document).ready(function () {
        init();
        function init() {
            var audioArray = document.getElementsByClassName('songs');
            var i = 0;
            audioArray[i].play();
            for (i = 0; i < audioArray.length - 1; ++i) {
                audioArray[i].addEventListener('ended', x()); //{
                //var currentSong = e.target;
                //var next = $(currentSong).nextAll('audio');
                //if (next.length) $(next[0]).trigger('play');
                //   i++;
                //  audioArray[i].play();
                //});
            }            
        }
        function x() {
            i++;
            audioArray[i].play();
        }
    })    
</script>
    *@
@*///////////////////////////////////////// This fires off when a song is ended////////////*@
<script type="text/javascript">
    function endSong(id)
    { 
        var   i                  = 0                                       ;  
        var   audioArray         = document.getElementsByClassName('songs'); //get all songs on the page 
        while (audioArray[i].id != id) { i++; }                              //check if we have iterated to the value of the song that has just played
        i                       += 1;                                        //move value to next song
        audioArray[i].play()                                               ; //play the next song
    }
</script>
@*/////////////////////////////////////// This stops all songs that are playing aside from the one we want to play ///////*@
<script type="text/javascript">
    function playSong(id)
    {
        var i          = 0                                                 ; 
        var audioArray = document.getElementsByClassName('songs')          ; //get all songs on page
        for (i = 0; i < audioArray.length; i++)                              //iterate through songs
        {
            if (audioArray[i].id != id) { audioArray[i].pause();}            //pause any song that doesnt have the id that was passed to the function
        }
    }
</script>
@*TODO :  REPLAY BUTTON &&&& COUNT REPLAYS VS PLAYS*@